Revert the solaris -m64 removal patch ... it breaks the compilation on both 32-bit and 64-bit platforms (32-bit is not supported by Monit on Solaris).
Solaris defaults to 32-bit if no -m64 is specified (even on LP64 platform), but 32-bit doesn't work, as we enable largefiles, which disables procfs which we use:

--8<--
In file included from /usr/include/procfs.h:23:0,
                 from src/process/sysdep_SOLARIS.c:75:
/usr/include/sys/procfs.h:42:2: error: #error "Cannot use procfs in the large file compilation environment"
In file included from src/process/sysdep_SOLARIS.c:88:0:
/usr/include/sys/swap.h:31:2: error: #error "Cannot use swapctl in the large files compilation environment"
gmake[2]: *** [src/process/sysdep_SOLARIS.o] Error 1
gmake[1]: *** [all-recursive] Error 1
gmake: *** [all] Error 2
--8<--